#ifndef BUBBLESHOOTER_BUBBLECOLOR_H
#define BUBBLESHOOTER_BUBBLECOLOR_H


enum BubbleColor {
    RED, YELLOW, BLUE, GREEN, PINK, PURPLE, BUBBLE_COLOR_SIZE, BLANK
};


#endif //BUBBLESHOOTER_BUBBLECOLOR_H
