//
// Created by giaol on 3/17/2022.
//

#ifndef BUBBLESHOOTER_SCREENSIZECARRIER_H
#define BUBBLESHOOTER_SCREENSIZECARRIER_H

const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 640;

#endif //BUBBLESHOOTER_SCREENSIZECARRIER_H
