#ifndef BUBBLESHOOTER_SCREENSIZECARRIER_H
#define BUBBLESHOOTER_SCREENSIZECARRIER_H

static const int SCREEN_WIDTH = 620;
static const int SCREEN_HEIGHT = 640;

#endif //BUBBLESHOOTER_SCREENSIZECARRIER_H
